[dependencies]
assert_approx_eq = "1.1.0"
assert_matches = "1.3.0"
backoff = "0.1.5"
backtrace = { version = "0.3", features = ["serialize-serde"] }
bech32 = "0.6.0"
bincode = "1.1.1"
bitcoin_hashes = "0.3.0"
bitvec = "0.10.1"
byteorder = "1.3.1"
bytes = "0.4.12"
cached = "0.8.0"
chashmap = "2.2.2"
chrono = "0.4.6"
clap = {version = "2.32"}
codespan = "0.1.3"
codespan-reporting = "0.1.4"
criterion = { version = "0.2.11", features = ["real_blackbox"] }
crossbeam = "0.7.1"
csv = "1.0.7"
curve25519-dalek = "1.1.3"
ctrlc = "3.1.3"
datatest = "0.3.5"
derive_deref = "1.0.2"
digest = "0.8.0"
ed25519-dalek = { version = "1.0.0-pre.1", features = ["serde"] }
failure = "0.1.3"
filecheck = "0.4.0"
futures = "0.1.25"
futures = { version = "=0.3.0-alpha.16", package = "futures-preview" }
futures_01 = { version = "0.1.25", package = "futures" }
futures01 = { package = "futures", version = "0.1.26" }
futures03 = { package = "futures-preview", version = "=0.3.0-alpha.16", features = ["compat"] }
getopts = "0.2.18"
get_if_addrs = "0.5.3"
grpcio = "0.4.3"
grpcio-sys = "0.4.4"
hex = "0.3.2"
hmac = "0.7.0"
itertools = "0.8.0"
jemalloc-sys= { version = "0.1.8", features = ["profiling", "unprefixed_malloc_on_supported_platforms"] }
jemallocator = { version = "0.1.8", features = ["alloc_trait", "profiling"] }
lalrpop = "0.16.3"
lalrpop-util = "0.16.3"
lazy_static = "1.3.0"
libc = "0.2.48"
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }
log = "0.4.6"
lru-cache = "0.1.1"
mktemp = "0.3"
mime = "0.3.2"
mirai-annotations = ">= 0.2.1"
num-derive = "0.2"
num-traits = "0.2"
pairing = "0.14.2"
parity-multiaddr = "0.4.0"
petgraph = "0.4"
pin-utils = "=0.1.0-alpha.4"
proc-macro2 = "0.4.27"
proptest = "0.9"
proptest-derive = "0.1.0"
protobuf = "2.7"
protobuf-codegen = "2.*"
protoc-grpcio = "0.3.1"
radix_trie = "0.1.3"
rand = "0.6.5"
rand_chacha = "0.1.1"
rand_core = "0.4.0"
rayon = "1.1"
regex = "1.1.6"
rental = "0.5.3"
ripemd160 = "0.8.0"
rust-crypto = "0.2"
rusty-fork = "0.2.1"
rust_decimal = "1.0.1"
rustyline = "4.1.0"
rmp-serde = "0.13.7"
quote = "0.6.11"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.38"
sha-1 = "0.8"
sha2 = "0.8.0"
sha3 = "0.8.2"
signal-hook = "0.1.9"
simple_logger = "0.5"
slog = { version = "2.4", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = "2.3"
slog-envlogger = "2.1.0"
slog-scope = "4.0"
slog-term = "2.4"
snow = { version = "0.5.2", features=["ring-accelerated"]}
stats_alloc = "0.1.8"
structopt = { version = "0.2.15", optional = true }
syn = { version = "0.15.26", features = ["derive"] }
tempdir = "0.3.7"
tempfile = "3.0.6"
termcolor = "1.0.4"
termion = "1.5.1"
thread-id = "3.3.0"
threshold_crypto = "0.3"
tiny-keccak = "1.4.2"
tokio = "0.1.16"
tokio-timer = "0.2.10"
tokio-retry = "0.2.0"
toml = "0.4"
ttl_cache = "0.4.2"
typed-arena = "1.4.1"
unsigned-varint = { version = "0.2.2", features = ["codec"] }
walkdir = "2.2.0"
yamux = "0.2.1"
x25519-dalek = "0.5.2"


[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"

[dependencies.prometheus]
version  = "0.4.2"
